# SPDX-FileCopyrightText: 2020 Kowainik
# SPDX-FileCopyrightText: 2022 Serokell <https://serokell.io/>
#
# SPDX-License-Identifier: MPL-2.0

name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

jobs:
  haskell:
    name: GHC ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc:
          - "9.0.1"
          - "8.10.7"
          - "8.8.4"
          - "8.6.5"

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    - uses: haskell/actions/setup@v1.2
      name: Setup Haskell Stack
      with:
        ghc-version: ${{ matrix.ghc }}

    - uses: actions/cache@v1
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack

    - name: Build
      run: |
        stack build --system-ghc --ghc-options '-Werror'

    - name: Haddock
      run: |
        stack haddock --system-ghc --no-haddock-deps

    - name: Test
      run: |
        stack test --system-ghc --ghc-options '-Werror'

  reuse:
    name: REUSE Compliance Check
    runs-on: ubuntu-latest
    steps:
    - name: Check
      uses: fsfe/reuse-action@v1
